---

- name: enable repos
  dnf:
    pkg: "{{ item }}"
  with_items:
    - python-dnf --allowerasing
    - libselinux-python
  become: yes

- name: enable repos
  dnf:
    pkg: "{{ item }}"
  with_items:
    - "http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/russianfedora-free-release-stable.noarch.rpm"
    - "http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/russianfedora-nonfree-release-stable.noarch.rpm"
    - "https://downloads.slack-edge.com/linux_releases/slack-2.2.1-0.1.fc21.x86_64.rpm"
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm"
  become: yes

- name: fedora-negativo17.repo
  copy:
    src: fedora-negativo17.repo
    dest: /etc/yum.repos.d/fedora-negativo17.repo
  become: yes

- name: install i3 packages
  dnf:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - vim
    - i3
    - i3-doc
    - i3lock
    - i3status
    - i3-ipc
    - py3status
    - atom
    - feh
    - gnome-settings-daemon
    - conky
    - conky-manager
    - chromium
    - dzen2
    - dunst
    - acpi
    - scrot
    - ImageMagick
    - python-pip
    - rdesktop
    - terminator
    - rofi
    - telegram-desktop
    - libselinux-python
    - screenfetch
    - fontawesome-fonts
    - spotify-client
    - steam
  become: yes

- name: copy wallpaper
  copy:
    src: pure-green-smoke.jpeg
    dest: ~/Pictures/pure-green-smoke.jpeg

- name: nice intro on 1st terminal
  lineinfile:
    line: screenfetch
    dest: ~/.bash_profile

- name: install i3 python pkg
  pip:
    name: i3-py
  become: yes

- name: create folders
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "~/.bin"
    - "~/.i3/backgrounds"
    - "~/.i3/icons"
    - "~/.i3/scripts"
    - "~/.i3/xbm-icons"
    - "~/.local/share/fonts"
    - "~/.config/terminator"

- name: put terminator config
  template:
    src: terminator-config.j2
    dest: "~/.config/terminator/config"


- name: put fonts
  copy:
    src: "{{ item }}"
    dest: "~/.local/share/fonts/{{ item }}"
  with_items:
    - AIcons.ttf
    #- fontawesome-webfont.ttf
    - icons.ttf

- name: initialise fonts
  shell: fc-cache -fv

- git:
    repo: "https://github.com/meskarune/i3lock-fancy.git"
    dest: "~/.i3/script/i3lock-fancy"

# i3blocks install
- git:
    repo: "https://github.com/vivien/i3blocks.git"
    dest: "/tmp/i3blocks"

- shell: make clean all
  args:
    chdir: "/tmp/i3blocks"

- shell: make install
  args:
    chdir: "/tmp/i3blocks"
  become: yes

- name: template i3 config
  template:
    src: '{{ item }}.j2'
    dest: '~/.i3/{{ item }}'
  with_items:
    - config
    - i3status.conf
    - i3blocks.conf
    - mail.sh
    - startup_apps.sh

- name: make executable
  file:
    path: '~/.i3/{{ item }}'
    mode: 'a+x'
  with_items:
    - mail.sh
    - startup_apps.sh

- name: i3 applications
  copy:
    src: '{{ item }}'
    dest: '~/.bin/{{ item }}'
    mode: 'a+x'
  with_items:
    - i3-exit
    - i3lock-wrapper
    - mws
    - gws
    - IconicWeather.sh
