---

- name: enable repos
  yum:
    pkg: "{{ item }}"
  with_items:
    - "http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/russianfedora-free-release-stable.noarch.rpm"
    - "http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/russianfedora-nonfree-release-stable.noarch.rpm"
    - "https://downloads.slack-edge.com/linux_releases/slack-2.2.1-0.1.fc21.x86_64.rpm"

- name: install i3 packages
  yum:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - i3
    - i3-doc
    - i3lock
    - i3status
    - i3-ipc
    - py3status
    - atom
    - feh
    - gnome-settings-daemon
    - conky
    - conky-manager
    - chromium
    - dzen2
    - acpi
    - scrot
    - ImageMagick
    - python-pip
    - rdesktop
    - terminator
    - rofi
    - telegram-desktop
  sudo: yes

- name: copy wallpaper
  copy:
    src: pure-green-smoke.jpeg
    dest: ~/Pictures/pure-green-smoke.jpeg

- name: install i3 python pkg
  pip:
    name: i3-py
  sudo: yes

- name: create folders
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "~/.bin"
    - "~/.i3/backgrounds"
    - "~/.i3/icons"
    - "~/.i3/scripts"
    - "~/.i3/xbm-icons"
    - "~/.local/share/fonts"

- name: put fonts
  copy:
    src: "{{ item }}"
    dest: "~/.local/share/fonts/{{ item }}"
  with_items:
    - AIcons.ttf
    - fontawesome-webfont.ttf
    - icons.ttf

- name: initilise fonts
  shell: fc-cache -fv

- git:
    repo: "https://github.com/meskarune/i3lock-fancy.git"
    dest: "~/.i3/script/i3lock-fancy"

# i3blocks install
- git:
    repo: "https://github.com/vivien/i3blocks.git"
    dest: "/tmp/i3blocks"

- shell: make clean all
  args:
    chdir: "/tmp/i3blocks"

- shell: make install
  args:
    chdir: "/tmp/i3blocks"
  sudo: yes

- name: template i3 config
  template:
    src: '{{ item }}.j2'
    dest: '~/.i3/{{ item }}'
  with_items:
    - config
    - i3status.conf
    - i3block.conf
    - mail.sh
    - startup_apps.sh

- name: i3 applications
  copy:
    src: '{{ item }}.j2'
    dest: '~/.bin/{{ item }}'
    mode: 'a+x'
  with_items:
    - i3-exit
    - i3lock-wrapper
    - mws
    - gws
    - battery
