---

- name: install i3 packages
  action: yum
  args:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - i3
    - i3-doc
    - i3lock
    - i3status
    - i3-ipc
    - py3status
    - feh
    - gnome-settings-daemon
    - conky
    - conky-manager
    - dzen2
    - acpi
    - scrot
    - ImageMagick
    - python-pip
    - rdesktop
  sudo: yes

- name: install i3 python pkg
  action: pip
  args:
    name: i3-py
  sudo: yes

- name: create folders
  action: file
  args:
    path: '{{ item }}'
    state: directory
  with_items:
    - "~/.i3/backgrounds"
    - "~/.i3/icons"
    - "~/.i3/scripts"
    - "~/.i3/xbm-icons"

- name: template i3 config
  action: template
  args:
    src: '{{ item }}.j2'
    dest: '~/.i3/{{ item }}'
  with_items:
    - config
    - i3status.conf
    - startup_apps.sh

- name: i3 applications
  action: template
  args:
    src: '{{ item }}.j2'
    dest: '/usr/bin/{{ item }}'
    owner: root
    mode: 'a+x'
  with_items:
    - i3-exit
    - i3lock-wrapper
    - mws
    - gws
    - rdp
  sudo: yes
