---
- name: add the VirtualBox repo
  action: template
  args:
    src: virtualbox.repo.j2
    dest: /etc/yum.repos.d/virtualbox.repo
  sudo: yes

- name: install required application
  action: yum
  args:
    state: installed
    name: '{{ item }}'
  with_items:
    - vagrant
    - VirtualBox
  sudo: yes

